site_name: Rained

plugins:
  - offline
  - search

nav:
  - 主页: index.md
  - 指南:
    - 简洁: brief.md
    - 安装和更新: install-updates.md
    - 用户界面: user-interface.md
    - 编辑关卡:
      - 概观: overview.md
      - 环境: env.md
      - 几何: geo.md
      - 瓦片: tiles.md
      - 相机: cameras.md
      - 灯光: light.md
      - 效果: effects.md
      - 道具: props.md
    - 渲染和游玩: rendering.md
    - 进一步阅读: resources.md
  - 开发: developing.md

theme:
  name: material
  language: zh
  favicon:
    img/favicon.ico
  logo:
    img/favicon.ico
  palette:
    scheme: slate
  features:
    - content.tabs.link
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

site_url: ""
docs_dir: "docs/zh"
site_dir: "dist/docs/zh"
use_directory_urls: False