site_name: Rained

plugins:
  - offline
  - search

nav:
  - Home: en/index.md
  - Manual:
    - Brief: en/brief.md
    - Installation and Updates: en/install-updates.md
    - User interface: en/user-interface.md
    - Asset management: en/asset-management.md
    - Editing the level:
      - Overview: en/overview.md
      - Environment: en/editors/env.md
      - Geometry: en/editors/geo.md
      - Tiles: en/editors/tiles.md
      - Cameras: en/editors/cameras.md
      - Light: en/editors/light.md
      - Effects: en/editors/effects.md
      - Props: en/editors/props.md
    - Playing your level: en/playing-your-level.md
    - Further reading: en/resources.md
  - Developing: en/developing.md

theme:
  name: material
  language: en
  favicon:
    img/favicon.ico
  logo:
    img/favicon.ico
  palette:
    scheme: slate
  features:
    - content.tabs.link
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra:
  alternate:
    - name: English
      link: /en/
      lang: en

site_url: ""
site_dir: "dist/docs"
use_directory_urls: False