site_name: Rained
plugins: []
nav:
  - Home: index.md
  - Manual:
    - Brief: brief.md
    - User interface: user-interface.md
    - Asset management: asset-management.md
    - Updates: updates.md
    - Editing the level:
      - Overview: overview.md
      - Environment: editors/env.md
      - Geometry: editors/geo.md
      - Tiles: editors/tiles.md
      - Cameras: editors/cameras.md
      - Light: editors/light.md
      - Effects: editors/effects.md
      - Props: editors/props.md
    - Playing your level: playing-your-level.md
    - Further reading: resources.md
theme:
  name: material
  features:
    - content.tabs.link
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

site_url: ""
site_dir: "dist/docs"
use_directory_urls: False