site_name: Rained

plugins:
  - offline
  - search

nav:
  - Home: index.md
  - Manual:
    - Brief: brief.md
    - Installation and Updates: install-updates.md
    - User interface: user-interface.md
    - Editing the level:
      - Overview: overview.md
      - Environment: env.md
      - Geometry: geo.md
      - Tiles: tiles.md
      - Cameras: cameras.md
      - Light: light.md
      - Effects: effects.md
      - Props: props.md
    - Rendering and playing: rendering.md
    - Further reading: resources.md
  - Developing: developing.md

theme:
  name: material
  language: en
  favicon:
    img/favicon.ico
  logo:
    img/favicon.ico
  palette:
    scheme: slate
  features:
    - content.tabs.link
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

site_url: ""
docs_dir: "docs/en"
site_dir: "dist/docs/en"
use_directory_urls: False