# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-tag

on:
  push:
    branches: [ "main" ]
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src/Drizzle
        dotnet run --project Drizzle.Transpiler
        cd ../..
        dotnet restore
    - name: Restore Cake Tool
      run: dotnet tool restore
    - name: Build windows
      run: dotnet cake --os=win-x64 --target=Package
    - name: Print file
      run: ls
