# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release build

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      full-release: true

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-x64
        path: ./artifacts/
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: win-x64
        path: ./artifacts/
    - name: Create Release
      uses: softprops/action-gh-release@v2
      id: create_release
      with:
        name: Draft Release
        draft: true
        make_latest: true
        body: Release vX-X-X.
        files: |
          ./artifacts/rained_linux-x64.tar.gz
          ./artifacts/rained_win-x64.zip