name: version-release

on:
  push:
    branches: 
      - "main"
    tags:
      - v*

jobs:
  windows-release-build:
    runs-on: windows-latest
    steps:
      - name: checkout git code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: |
          cd src/Drizzle
          dotnet restore
          cd ../..
      - name: Restore Cake Tool
        run: dotnet tool restore
      - name: Linux Package
        run: dotnet cake --os=linux-x64 --target=Package
      - name: Windows Package
        run: dotnet cake --os=win-x64 --target=Package
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: ./artifacts/rained_linux-x64.tar.gz
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: ./artifacts/rained_win-x64.zip

  create_release:
    needs: [windows-release-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-x64
        path: ./artifacts/
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: win-x64
        path: ./artifacts/
    - name: Remove Old Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release delete nightly --cleanup-tag -y
    - name: Create Release
      uses: softprops/action-gh-release@v2
      id: create_release
      with:
        tag_name: latest
        files: |
          ./artifacts/rained_linux-x64.tar.gz
          ./artifacts/rained_win-x64.zip